# Generated by Django 2.2 on 2019-05-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('t', 'Transversal'), ('e', 'Estratégico')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('estrategia', models.CharField(blank=True, max_length=200)),
                ('ejeTransversal', models.CharField(choices=[('1', 'Desarrollo Integral'), ('2', 'Desarrollo Social y Humano'), ('3', 'Promoción Económica y Medio Ambiente'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Combate a la Corrupción y Participación Ciudadana')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivo.Objetivo')),
            ],
            options={
                'unique_together': {('objetivo', 'dependencia')},
            },
        ),
    ]
