# Generated by Django 2.2 on 2019-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300)),
                ('tipo', models.CharField(choices=[('t', 'Transversal'), ('e', 'Estratégico')], max_length=300)),
                ('descripcion', models.CharField(blank=True, max_length=1000)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('estrategia', models.CharField(blank=True, max_length=1000)),
                ('ejeTransversal', models.CharField(choices=[('1', 'Desarrollo Integral'), ('2', 'Desarrollo Social y Humano'), ('3', 'Promoción Económica y Medio Ambiente'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Combate a la Corrupción y Participación Ciudadana')], max_length=300)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=3)),
                ('dependencia', models.ManyToManyField(blank=True, to='dependencia.Dependencia')),
            ],
        ),
    ]
