# Generated by Django 2.2 on 2019-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='ejeTransversal',
            field=models.CharField(choices=[('1', 'Desarrollo Integral'), ('2', 'Desarrollo Social y Humano'), ('3', 'Promoción Económica y Medio Ambiente'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Combate a la Corrupción y Participación Ciudadana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='numero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='tipo',
            field=models.CharField(choices=[('t', 'Transversal'), ('e', 'Estratégico')], max_length=100),
        ),
    ]
