# Generated by Django 2.2 on 2019-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='numero',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
