# Generated by Django 2.2 on 2019-06-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0002_auto_20190604_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivo',
            options={'verbose_name': 'Objetivos transversales/estratégicos'},
        ),
    ]
