# Generated by Django 2.2 on 2019-05-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0003_auto_20190518_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='estrategia',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='tipo',
            field=models.CharField(choices=[('t', 'Transversal'), ('e', 'Estratégico')], max_length=300),
        ),
    ]
