# Generated by Django 2.2 on 2019-06-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0003_auto_20190604_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivo',
            options={'verbose_name': 'Objetivo transversal/estratégico', 'verbose_name_plural': 'Objetivos transversales/estratégicos'},
        ),
    ]
