# Generated by Django 2.2 on 2019-05-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_auto_20190518_1842'),
        ('objetivo', '0004_auto_20190518_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='dependencia',
            field=models.ManyToManyField(blank=True, null=True, to='dependencia.Dependencia'),
        ),
    ]
