# Generated by Django 2.2 on 2019-05-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0005_objetivo_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='dependencia',
            field=models.ManyToManyField(blank=True, to='dependencia.Dependencia'),
        ),
    ]
