# Generated by Django 2.2 on 2019-05-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0006_auto_20190518_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallesObjetivo',
        ),
    ]
