# Generated by Django 2.2 on 2019-05-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0007_delete_detallesobjetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='numero',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
