# Generated by Django 2.2 on 2019-05-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0008_auto_20190520_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='estado',
            field=models.CharField(default='A', max_length=3),
        ),
    ]
