# Generated by Django 2.2 on 2019-05-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0009_objetivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=3),
        ),
    ]
