# Generated by Django 2.2 on 2019-05-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('s', 'Secretaría'), ('g', 'Dirección general'), ('o', 'Otro')], max_length=30)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('d', 'Dependencia'), ('p', 'Paramunicipal')], max_length=30)),
                ('adscrita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dependencia.Raiz')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dependencia.Dependencia')),
            ],
        ),
    ]
