# Generated by Django 2.2 on 2019-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiz',
            name='tipo',
            field=models.CharField(choices=[('s', 'Secretaría'), ('g', 'Dirección general'), ('o', 'Otro')], max_length=30),
        ),
    ]
