# Generated by Django 2.2 on 2019-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('d', 'Dependencia'), ('p', 'Paramunicipal')], max_length=30),
        ),
    ]
