# Generated by Django 2.2 on 2019-05-19 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='adscrita',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='adscrita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dependencia.Raiz'),
        ),
    ]
