# Generated by Django 2.2 on 2019-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='adscrita',
            field=models.ManyToManyField(blank=True, to='dependencia.Raiz'),
        ),
    ]
