# Generated by Django 2.2 on 2019-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_auto_20190515_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='adscrita',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='adscrita',
            field=models.ManyToManyField(blank=True, null=True, to='dependencia.Raiz'),
        ),
    ]
