# Generated by Django 2.2 on 2019-05-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_auto_20190508_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('secretario', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='A', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='dependencia',
            name='secretaria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependencia.Secretaria'),
        ),
    ]
