# Generated by Django 2.2 on 2019-05-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0003_auto_20190509_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('s', 'Secretaría'), ('o', 'Otro')], max_length=30)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='A', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='secretaria',
        ),
        migrations.DeleteModel(
            name='Secretaria',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='adscrita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependencia.Raiz'),
        ),
    ]
