# Generated by Django 2.2 on 2019-06-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0003_auto_20190604_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='dependencia',
            options={'verbose_name': 'Dependencia', 'verbose_name_plural': 'Dependencias'},
        ),
        migrations.AlterModelOptions(
            name='raiz',
            options={'verbose_name': 'Secretaría/Dirección General', 'verbose_name_plural': 'Secretarías/Direcciones Generales'},
        ),
    ]
