# Generated by Django 2.2 on 2019-08-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0006_departamento_tienedepartamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='tieneDepartamentos',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='tieneDepartamentos',
            field=models.BooleanField(default=True, verbose_name='¿Tiene departamentos?'),
        ),
    ]
