# Generated by Django 2.2 on 2019-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0007_auto_20190810_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Catálogo de alcance',
            },
        ),
        migrations.AddField(
            model_name='dependencia',
            name='alcance',
            field=models.ManyToManyField(blank=True, to='dependencia.Alcance', verbose_name='Alcance de la dependencia'),
        ),
    ]
