# Generated by Django 2.2 on 2019-10-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0008_auto_20191015_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcance',
            name='nombre',
            field=models.CharField(max_length=300, verbose_name='Descripción de alcance'),
        ),
    ]
