# Generated by Django 2.2 on 2019-05-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopaterno', models.CharField(blank=True, max_length=30)),
                ('apellidomaterno', models.CharField(blank=True, max_length=30)),
                ('edad', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('tipoUsuario', models.CharField(choices=[('s', 'Super usuario'), ('a', 'Administrador'), ('e', 'Enlace'), ('i', 'Inspector')], max_length=30, verbose_name='Tipo de usuario')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia', verbose_name='Dependencia a la que pertenece')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
