# Generated by Django 2.2 on 2019-05-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('s', 'Super usuarios'), ('a', 'Administrador'), ('e', 'Enlace'), ('i', 'Inspector')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
