# Generated by Django 2.2 on 2019-07-19 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programaOperativo', '0030_auto_20190710_1206'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('p', 'Programada'), ('t', 'Por revisar'), ('i', 'Inactiva'), ('r', 'Válida'), ('n', 'No válida')], default='p', max_length=30)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
