# Generated by Django 2.2.1 on 2019-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopaterno', models.CharField(blank=True, max_length=30)),
                ('apellidomaterno', models.CharField(blank=True, max_length=30)),
                ('edad', models.IntegerField(blank=True, max_length=30)),
            ],
        ),
    ]
