# Generated by Django 2.2 on 2019-05-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(default='acosta', max_length=30, verbose_name='Apellido(s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.EmailField(default='jesus_acosta1996@hotmail.com', max_length=40, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(default='Carlos', max_length=30, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dependencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dependencia.Dependencia', verbose_name='Dependencia a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('s', 'Super usuario'), ('a', 'Administrador'), ('e', 'Enlace'), ('i', 'Inspector')], max_length=30, verbose_name='Tipo de usuario'),
        ),
    ]
