# Generated by Django 2.2 on 2019-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipoUsuario',
            field=models.CharField(choices=[('s', 'Super usuario'), ('a', 'Administrador'), ('e', 'Enlace'), ('i', 'Inspector')], default='s', max_length=30),
            preserve_default=False,
        ),
    ]
