# Generated by Django 2.2 on 2019-07-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactividad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2019-07-02'),
            preserve_default=False,
        ),
    ]
