# Generated by Django 2.2 on 2019-05-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_departamento'),
        ('users', '0002_auto_20190504_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dependencia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia'),
            preserve_default=False,
        ),
    ]
