# Generated by Django 2.2 on 2019-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190508_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('s', 'Super usuario'), ('a', 'Administrador'), ('e', 'Enlace'), ('i', 'Inspector')], max_length=30),
        ),
    ]
