# Generated by Django 2.2 on 2019-07-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_logactividad_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogActividad',
        ),
    ]
