# Generated by Django 2.2 on 2019-05-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dependencia',
        ),
    ]
