# Generated by Django 2.2 on 2019-05-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_dependencia'),
        ('users', '0002_persona'),
    ]

    operations = [
    ]
