# Generated by Django 2.2 on 2019-05-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_departamento'),
        ('users', '0005_merge_20190506_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=20170404),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dependencia',
            field=models.ForeignKey(default=2017040410000, on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
