# Generated by Django 2.2 on 2019-05-07 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190507_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 7, 22, 11, 59, 906312, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 5, 7, 22, 12, 8, 348010, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
