# Generated by Django 2.2 on 2019-05-07 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_departamento'),
        ('users', '0013_auto_20190507_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 7, 22, 23, 29, 867230, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dependencia',
            field=models.ForeignKey(default=datetime.datetime(2019, 5, 7, 22, 23, 35, 803702, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
    ]
