# Generated by Django 2.2 on 2019-05-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPoblacionObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PoblacionObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('h', 'Hombre'), ('m', 'Mujer'), ('a', 'Ambos'), ('l', 'LGBT')], max_length=30, verbose_name='Sexo')),
                ('edadDesde', models.CharField(max_length=30, verbose_name='Edad desde')),
                ('edadHasta', models.CharField(max_length=30, verbose_name='Edad hasta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.CategoriaPoblacionObjetivo')),
            ],
        ),
    ]
