# Generated by Django 2.2 on 2019-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0002_auto_20190604_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Clasificadores de gastos',
            },
        ),
    ]
