# Generated by Django 2.2 on 2019-06-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0004_conceptogasto_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPoblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('edadDesde', models.CharField(max_length=20, verbose_name='Edad desde')),
                ('edadHasta', models.CharField(max_length=20, verbose_name='Edad hasta')),
            ],
            options={
                'verbose_name': 'Categoría de población',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='GruposVulnerables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Grupos vulnerables',
            },
        ),
        migrations.CreateModel(
            name='SectorSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sectores sociales',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ubicación',
            },
        ),
        migrations.RemoveField(
            model_name='poblacionobjetivo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaPoblacionObjetivo',
        ),
    ]
