# Generated by Django 2.2 on 2019-06-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0012_auto_20190606_1726'),
        ('indicador', '0005_auto_20190606_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoblacionObjetivo',
        ),
    ]
