# Generated by Django 2.2 on 2019-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0006_delete_poblacionobjetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriapoblacion',
            name='sexo',
            field=models.CharField(choices=[('h', 'Hombre'), ('m', 'Mujer'), ('a', 'Ambos')], default='a', max_length=30),
            preserve_default=False,
        ),
    ]
