# Generated by Django 2.2 on 2019-06-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0009_auto_20190612_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapoblacion',
            options={'verbose_name': 'Categoría de población', 'verbose_name_plural': 'Categorías de población'},
        ),
        migrations.AlterModelOptions(
            name='clasificaciongasto',
            options={'verbose_name': 'Clasificadores de gastos', 'verbose_name_plural': 'Clasificadores de gastos'},
        ),
        migrations.AlterModelOptions(
            name='conceptogasto',
            options={'verbose_name': 'Concepto por gasto', 'verbose_name_plural': 'Conceptos por gasto'},
        ),
        migrations.AlterModelOptions(
            name='escolaridad',
            options={'verbose_name': 'Escolaridad', 'verbose_name_plural': 'Escolaridades'},
        ),
        migrations.AlterModelOptions(
            name='gruposvulnerables',
            options={'verbose_name': 'Grupo vulnerable', 'verbose_name_plural': 'Grupos vulnerables'},
        ),
        migrations.AlterModelOptions(
            name='sectoreconomico',
            options={'verbose_name': 'Sector económico', 'verbose_name_plural': 'Sectores económicos'},
        ),
        migrations.AlterModelOptions(
            name='sectorsocial',
            options={'verbose_name': 'Sector social', 'verbose_name_plural': 'Sectores sociales'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
