# Generated by Django 2.2 on 2019-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0010_auto_20190619_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del periodo')),
                ('fechaInicial', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaFinal', models.DateField(verbose_name='Fecha de final')),
            ],
        ),
    ]
