# Generated by Django 2.2 on 2019-08-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0012_auto_20190624_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoGobierno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del periodo')),
                ('fehcaInicial', models.DateField(verbose_name='Fecha de inicio del periodo')),
                ('fechaFinal', models.DateField(verbose_name='Fecha fianl del periodo')),
            ],
            options={
                'verbose_name': 'Periodo de gobierno',
                'verbose_name_plural': 'Periodos de gobierno',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del periodo')),
                ('descendente', models.BooleanField(default=False, verbose_name='¿Es descendente?')),
                ('cualitativa', models.BooleanField(default=False, verbose_name='¿Es cualitativa?')),
                ('noPublica', models.BooleanField(default=False, verbose_name='¿No es pública?')),
                ('meta', models.IntegerField(verbose_name='Meta numérica')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.PeriodoGobierno', verbose_name='Periodo de gobierno')),
            ],
            options={
                'verbose_name': 'Meta de actividad',
                'verbose_name_plural': 'Metas de actividades',
            },
        ),
    ]
