# Generated by Django 2.2 on 2019-08-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0013_meta_periodogobierno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Periodo de gastos', 'verbose_name_plural': 'Periodos de gastos'},
        ),
    ]
