# Generated by Django 2.2 on 2019-08-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0016_auto_20190809_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodogobierno',
            name='permitirCambios',
            field=models.BooleanField(default=True, verbose_name='¿Permitir cambios?'),
        ),
    ]
