# Generated by Django 2.2 on 2019-08-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0019_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='periodoGobierno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicador.PeriodoGobierno', verbose_name='Periodo de gobierno a graficar'),
        ),
    ]
