# Generated by Django 2.2 on 2019-10-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0047_auto_20191015_0841'),
        ('indicador', '0020_auto_20190819_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaPoblacion',
        ),
        migrations.DeleteModel(
            name='Escolaridad',
        ),
        migrations.DeleteModel(
            name='GruposVulnerables',
        ),
        migrations.DeleteModel(
            name='SectorEconomico',
        ),
        migrations.DeleteModel(
            name='SectorSocial',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variable',
            name='indicador',
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
