# Generated by Django 2.2 on 2019-11-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0022_unidadmedida_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
