# Generated by Django 2.2 on 2019-11-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0023_recursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursos',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
