# Generated by Django 2.2 on 2019-05-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencia', '0002_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoTransversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('estrategia', models.CharField(blank=True, max_length=200)),
                ('ejeTransversal', models.CharField(choices=[('1', 'Desarrollo Integral'), ('2', 'Desarrollo Social y Humano'), ('3', 'Promoción Económica y Medio Ambiente'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Combate a la Corrupción y Participación Ciudadana')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesObjetivoTransversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia')),
                ('objetivoTransversal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivoTransversal.ObjetivoTransversal')),
            ],
            options={
                'unique_together': {('objetivoTransversal', 'dependencia')},
            },
        ),
    ]
