# Generated by Django 2.2 on 2019-05-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivoTransversal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallesObjetivoTransversal',
        ),
    ]
