# Generated by Django 2.2 on 2019-05-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_departamento'),
        ('objetivoTransversal', '0002_delete_detallesobjetivotransversal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesObjetivoTransversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia')),
                ('objetivoTransversal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivoTransversal.ObjetivoTransversal')),
            ],
            options={
                'unique_together': {('objetivoTransversal', 'dependencia')},
            },
        ),
    ]
