# Generated by Django 2.2 on 2019-05-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivoTransversal', '0003_detallesobjetivotransversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivotransversal',
            name='nombre',
            field=models.CharField(default='adsdasd', max_length=100),
            preserve_default=False,
        ),
    ]
