# Generated by Django 2.2 on 2019-05-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivoTransversal', '0004_objetivotransversal_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivotransversal',
            name='nombre',
        ),
    ]
