# Generated by Django 2.2 on 2019-05-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivoTransversal', '0005_remove_objetivotransversal_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivotransversal',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='objetivotransversal',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
