# Generated by Django 2.2 on 2019-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivoTransversal', '0006_auto_20190507_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivotransversal',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='objetivotransversal',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
