# Generated by Django 2.2 on 2019-05-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivo', '0001_initial'),
        ('dependencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('tipoPrograma', models.CharField(blank=True, choices=[('i', 'Institucional'), ('e', 'Enfocado'), ('d', 'Distintivo'), ('p', 'Piloto'), ('f', 'Foro'), ('c', 'Campaña')], max_length=30, null=True, verbose_name='Tipo de programa')),
                ('objetivos', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Objetivos')),
                ('estrategias', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Estrategias')),
                ('beneficiarios', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Beneficiarios')),
                ('justificacion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Justificación')),
                ('problematicaSocial', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Problemática social')),
                ('acciones', models.ManyToManyField(blank=True, to='programaOperativo.Acciones')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dependencia.Dependencia')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objetivo.Objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='¿Qué actividad se realiza?')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descríbela brevemente')),
                ('presupuestoProgramado', models.CharField(max_length=300, verbose_name='Presupuesto asignado a esta actividad')),
                ('presupuestoEjercido', models.CharField(blank=True, max_length=300, null=True)),
                ('personasInvolucradas', models.CharField(blank=True, max_length=10, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='')),
                ('fecha_in', models.DateField(verbose_name='Día en el que se realiza')),
                ('fecha_fi', models.DateField(verbose_name='Día en el que se finaliza')),
                ('latitud', models.CharField(blank=True, max_length=300, null=True)),
                ('longitud', models.CharField(blank=True, max_length=300, null=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Acciones', verbose_name='Acción a la que corresponde')),
                ('programaoperativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.ProgramaOperativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
