# Generated by Django 2.2 on 2019-05-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivoTransversal', '0003_detallesobjetivotransversal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=600)),
                ('tipoPrograma', models.CharField(choices=[('i', 'Institucional'), ('e', 'Enfocado'), ('d', 'Distintivo'), ('p', 'Piloto'), ('f', 'Foro'), ('c', 'Campaña')], max_length=30)),
                ('objetivos', models.CharField(max_length=600)),
                ('estrategias', models.CharField(max_length=600)),
                ('beneficiarios', models.CharField(max_length=600)),
                ('justificacion', models.CharField(max_length=600)),
                ('problematicaSocial', models.CharField(max_length=600)),
                ('objetivoTransversal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivoTransversal.ObjetivoTransversal')),
            ],
        ),
    ]
