# Generated by Django 2.2 on 2019-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(max_length=300, verbose_name='Descripción breve'),
        ),
    ]
