# Generated by Django 2.2 on 2019-05-18 22:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programaOperativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividad',
            new_name='Actividades',
        ),
    ]
