# Generated by Django 2.2 on 2019-05-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
        ('programaOperativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaoperativo',
            name='dependencia',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='dependencia.Dependencia'),
            preserve_default=False,
        ),
    ]
