# Generated by Django 2.2 on 2019-05-18 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programaOperativo', '0002_auto_20190518_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('fecha_in', models.DateField()),
                ('fecha_fi', models.DateField()),
                ('programaoperativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.ProgramaOperativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Actividades',
        ),
    ]
