# Generated by Django 2.2 on 2019-05-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0001_initial'),
        ('programaOperativo', '0003_auto_20190527_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='objetivo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='objetivo.Objetivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('p', 'Programada'), ('t', 'Terminada'), ('i', 'Inactiva'), ('r', 'Revisada')], default='p', max_length=30),
        ),
    ]
