# Generated by Django 2.2 on 2019-05-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0003_auto_20190518_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='actividad',
            name='personasInvolucradas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='presupuestoEjercido',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='presupuestoProgramado',
            field=models.CharField(default='300000', max_length=300),
            preserve_default=False,
        ),
    ]
