# Generated by Django 2.2 on 2019-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0004_auto_20190529_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='nombre',
            field=models.CharField(max_length=700),
        ),
    ]
