# Generated by Django 2.2 on 2019-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0004_auto_20190518_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaoperativo',
            name='beneficiarios',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='programaoperativo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='programaoperativo',
            name='estrategias',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='programaoperativo',
            name='justificacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='programaoperativo',
            name='objetivos',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='programaoperativo',
            name='problematicaSocial',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='programaoperativo',
            name='tipoPrograma',
            field=models.CharField(blank=True, choices=[('i', 'Institucional'), ('e', 'Enfocado'), ('d', 'Distintivo'), ('p', 'Piloto'), ('f', 'Foro'), ('c', 'Campaña')], max_length=30, null=True),
        ),
    ]
