# Generated by Django 2.2 on 2019-05-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
        ('programaOperativo', '0005_auto_20190529_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='poblacionObjetivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicador.PoblacionObjetivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programaoperativo',
            name='estado',
            field=models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=30),
        ),
    ]
