# Generated by Django 2.2 on 2019-05-30 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0006_auto_20190529_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 30, 10, 0, 52, 23295)),
            preserve_default=False,
        ),
    ]
