# Generated by Django 2.2 on 2019-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0007_actividad_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('p', 'Programada'), ('t', 'Terminada'), ('i', 'Inactiva'), ('r', 'Revisada'), ('n', 'No válida')], default='p', max_length=30),
        ),
    ]
