# Generated by Django 2.2 on 2019-06-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0008_auto_20190604_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acciones',
            options={'verbose_name': 'Acciones de programas operativos'},
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='programaoperativo',
            options={'verbose_name': 'Programas operativos'},
        ),
    ]
