# Generated by Django 2.2 on 2019-06-05 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0002_auto_20190604_1415'),
        ('programaOperativo', '0009_auto_20190604_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Clasificadores de gastos',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechaActualizada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechaRegistrada',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='presupuestoProgramado',
            field=models.CharField(max_length=300, verbose_name='Presupuesto comprometido en esta actividad'),
        ),
        migrations.CreateModel(
            name='DetallesGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=100)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Actividad')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.ClasificacionGasto')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.ConceptoGasto')),
            ],
            options={
                'verbose_name': 'Detalles de gasto por actividades',
            },
        ),
    ]
