# Generated by Django 2.2 on 2019-06-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0010_auto_20190605_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesgasto',
            name='clasificacion',
        ),
        migrations.DeleteModel(
            name='ClasificacionGasto',
        ),
    ]
