# Generated by Django 2.2 on 2019-06-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0008_sectoreconomico'),
        ('programaOperativo', '0012_auto_20190606_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='sectorEconomico',
            field=models.ManyToManyField(blank=True, to='indicador.SectorEconomico'),
        ),
    ]
