# Generated by Django 2.2 on 2019-06-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0013_acciones_sectoreconomico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='presupuestoEjercido',
        ),
    ]
