# Generated by Django 2.2 on 2019-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0016_remove_programaoperativo_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaoperativo',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
