# Generated by Django 2.2 on 2019-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0017_auto_20190610_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='beneficiarios',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de beneficiarios/Asistentes'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='personasInvolucradas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Personal involucrado'),
        ),
    ]
