# Generated by Django 2.2 on 2019-06-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0010_auto_20190619_1326'),
        ('programaOperativo', '0020_auto_20190619_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesgasto',
            options={'verbose_name': 'Detalle de gasto por acción', 'verbose_name_plural': 'Detalles de gasto por acción'},
        ),
        migrations.AddField(
            model_name='detallesgasto',
            name='accion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Acciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallesgasto',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Actividad'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesgasto',
            unique_together={('accion', 'gasto')},
        ),
    ]
