# Generated by Django 2.2 on 2019-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0024_auto_20190621_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción breve'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=500, verbose_name='Actividad'),
        ),
    ]
