# Generated by Django 2.2 on 2019-06-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0012_auto_20190624_1358'),
        ('programaOperativo', '0026_auto_20190624_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallesgasto',
            unique_together={('accion', 'gasto', 'periodo')},
        ),
    ]
