# Generated by Django 2.2 on 2019-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0027_auto_20190625_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='meta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
