# Generated by Django 2.2 on 2019-07-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0028_acciones_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='meta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
