# Generated by Django 2.2 on 2019-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0029_auto_20190701_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='descripcionMeta',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción de la meta'),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='meta',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta numérica'),
        ),
    ]
