# Generated by Django 2.2 on 2019-07-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0005_auto_20190724_0849'),
        ('programaOperativo', '0031_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaoperativo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dependencia.Departamento', verbose_name='Departamento'),
        ),
    ]
