# Generated by Django 2.2 on 2019-07-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0032_programaoperativo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programaOperativo.Actividad'),
        ),
    ]
