# Generated by Django 2.2 on 2019-07-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0033_auto_20190729_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Actividad'),
        ),
    ]
