# Generated by Django 2.2 on 2019-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0014_auto_20190808_1218'),
        ('programaOperativo', '0035_auto_20190808_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciones',
            name='meta',
        ),
        migrations.AddField(
            model_name='acciones',
            name='meta',
            field=models.ManyToManyField(blank=True, to='indicador.Meta'),
        ),
    ]
