# Generated by Django 2.2 on 2019-08-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0037_auto_20190809_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoanualasignado',
            name='permitirModificar',
            field=models.BooleanField(default=True, verbose_name='¿Permitir modificar?'),
        ),
    ]
