# Generated by Django 2.2 on 2019-08-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0017_periodogobierno_permitircambios'),
        ('programaOperativo', '0038_gastoanualasignado_permitirmodificar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gastoanualasignado',
            unique_together={('programaOperativo', 'periodoGobierno')},
        ),
    ]
