# Generated by Django 2.2 on 2019-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0039_auto_20190810_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='cualitatica',
            field=models.BooleanField(default=False, verbose_name='¿Es una acción cualitativa?'),
        ),
        migrations.AddField(
            model_name='acciones',
            name='publica',
            field=models.BooleanField(default=True, verbose_name='¿Es una acción pública?'),
        ),
    ]
