# Generated by Django 2.2 on 2019-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0041_acciones_multiplicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciones',
            name='multiplicador',
        ),
        migrations.AddField(
            model_name='actividad',
            name='multiplicador',
            field=models.IntegerField(default=1),
        ),
    ]
