# Generated by Django 2.2 on 2019-08-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0042_auto_20190814_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acciones',
            old_name='cualitatica',
            new_name='cualitativa',
        ),
    ]
