# Generated by Django 2.2 on 2019-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0043_auto_20190814_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('p', 'Programada'), ('t', 'Por revisar'), ('i', 'Inactiva'), ('r', 'Principal'), ('s', 'Secundaria'), ('n', 'No válida')], default='p', max_length=30),
        ),
    ]
