# Generated by Django 2.2 on 2019-08-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0045_configuracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
