# Generated by Django 2.2 on 2019-10-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaOperativo', '0046_delete_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciones',
            name='categoriaPoblacion',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='escolaridad',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='gruposVulnerables',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='sectorEconomico',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='sectorSocial',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='multiplicador',
            field=models.IntegerField(default=1, verbose_name='¿Cuántas veces se realizó esta actividad?'),
        ),
    ]
