# Generated by Django 2.2 on 2019-10-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0022_unidadmedida_variable'),
        ('programaOperativo', '0049_beneficiariosactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=10)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Acciones')),
                ('periodoGobierno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.PeriodoGobierno')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.Variable')),
            ],
        ),
    ]
