# Generated by Django 2.2 on 2019-10-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0022_unidadmedida_variable'),
        ('programaOperativo', '0051_auto_20191028_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Actividad')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.Variable')),
            ],
            options={
                'verbose_name': 'Variable de la actividad',
                'verbose_name_plural': 'Variables de las actividades',
            },
        ),
    ]
