# Generated by Django 2.2 on 2019-10-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0022_unidadmedida_variable'),
        ('programaOperativo', '0052_variableactividad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variableactividad',
            unique_together={('variable', 'actividad')},
        ),
    ]
