# Generated by Django 2.2 on 2019-11-07 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0024_auto_20191107_1326'),
        ('programaOperativo', '0053_auto_20191029_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesgasto',
            name='programaOperativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.ProgramaOperativo'),
        ),
        migrations.AlterField(
            model_name='detallesgasto',
            name='accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programaOperativo.Acciones', verbose_name='Acción'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesgasto',
            unique_together={('programaOperativo', 'gasto', 'periodo')},
        ),
    ]
